### ISSUE TITLE
Clean UP & Dockerization eos6o0z

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos6o0z#1]

**Comment by GemmaTuron** [comment]
@samuelmaina 

This model is pending to be updated:
- the latest PR is failing
- The source of information (QM7 or QM7b) is not yet clear

**Comment by samuelmaina** [comment]
I have corrected the PR error but when I push the commit the workflows did not rerun by default.Maybe you can run on your side.I have not yet had a meeting with my mentor but the source code points to the general grover publication with many models. An example of QM7  from the original source code is a float column which can be seen from https://github.com/tencent-ailab/grover/blob/main/exampledata/finetune/qm7.csv.

**Comment by GemmaTuron** [comment]
I have set the re-run of the workflow, sorry about that

Then we can assume we are using only the QM7 data and therefore it's the description and output that should be changed in the metadata? I'll take care of this once the model is working.
